# Generated by Django 4.1.5 on 2023-03-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turfdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=20)),
                ('t_location', models.CharField(max_length=20)),
                ('t_cat', models.CharField(max_length=10)),
                ('t_price', models.CharField(max_length=10)),
                ('t_image', models.ImageField(upload_to='Turf')),
            ],
        ),
    ]
