# Generated by Django 4.1.5 on 2023-03-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_turfdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfdb',
            name='t_location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='turfdb',
            name='t_name',
            field=models.CharField(max_length=40),
        ),
    ]
