# Generated by Django 4.1.5 on 2023-03-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_turfdb_t_location_alter_turfdb_t_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfdb',
            name='t_location',
            field=models.CharField(max_length=40),
        ),
    ]
