# Generated by Django 4.1.5 on 2023-03-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_turfdb_t_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfdb',
            name='t_cat',
            field=models.CharField(default='', max_length=10),
        ),
    ]
