# Generated by Django 4.1.5 on 2023-03-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_turfdb_t_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfdb',
            name='t_cat',
            field=models.CharField(default='', max_length=30),
        ),
    ]
