# Generated by Django 4.1.5 on 2023-03-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_turfdb_t_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=20)),
                ('m_password', models.CharField(max_length=20)),
                ('m_mail', models.CharField(max_length=20)),
                ('m_turf', models.CharField(max_length=40)),
                ('m_image', models.ImageField(upload_to='Manager')),
            ],
        ),
    ]
