# Generated by Django 4.1.5 on 2023-03-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_turf', models.CharField(max_length=40)),
                ('b_date', models.DateField()),
                ('b_time', models.CharField(max_length=10)),
            ],
        ),
    ]
