# Generated by Django 4.1.5 on 2023-03-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_bookdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
