# Generated by Django 4.1.5 on 2023-03-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_bookdb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='b_name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='bookdb',
            name='b_password',
            field=models.CharField(default='', max_length=15),
        ),
    ]
