# Generated by Django 4.1.5 on 2023-03-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_bookdb_b_name_bookdb_b_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdb',
            name='b_password',
        ),
        migrations.AddField(
            model_name='bookdb',
            name='b_price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
