# Generated by Django 4.1.5 on 2023-03-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_bookdb_b_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='b_umail',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='bookdb',
            name='b_umob',
            field=models.CharField(default='', max_length=40),
        ),
    ]
